### PR TITLE
Update Code Of Covenant to 2.0

### PR DESCRIPTION
**Pull request by XAMPPRocky**

### CODE REVIEW

**Comment by davidpdrsn** [comment]
@lpil @arirawr Does that mean the current version of this thats in the template is out of date?

**Comment by lpil** [comment]
Aye, though we've just updated the template so will be ok

**Comment by arirawr** [comment]
@XAMPPRocky please also update the badge in the readme! :)

**Comment by davidpdrsn** [comment]
@XAMPPRocky @arirawr I fixed that real quick in 67b5eebf538d0

**Pull request merged**
